apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # List clusters
          - list:
              elements:
                - cluster: https://kubernetes.default.svc
                  appName: sampleapp-dev
                - cluster: https://192.168.111.132:8443
                  appName: sampleapp-stage
          # List namespaces
          - list:
              elements:
                - namespace: dev
                - namespace: preprod
  template:
    metadata:
      name: "{{appName}}-{{namespace}}"  # Include namespace in app name
    spec:
      project: default
      source:
        repoURL: https://github.com/gititc778/gitops
        targetRevision: master
        path: sampleapp
      destination:
        server: "{{cluster}}"
        namespace: "{{namespace}}"
